feat: about section
fs-jun24-team2/phone-catalog pull request #51
Opened 2024-09-20 14:10 UTC by NavI-Rap0

about section

2024-09-20 14:11 UTC, AndriiZakharenko commented
👀

2024-09-20 14:11 UTC, AndriiZakharenko approved these changes

2024-09-20 17:19 UTC, iyehorova requested changes
Good job.
Please check a comment below

2024-09-20 17:19 UTC, iyehorova commented on src/modules/ProductDetailsPage/About/About.tsx
> +        <div key={index} className={styles.about__text_container}>
Please, split the code into separate components. All the code after `description.map((item, index) => (`  in one component and after `item.text.map((paragraph, idx) => (` in another.

2024-09-21 18:42 UTC, iyehorova approved these changes

2024-09-21 18:43 UTC, merged