feat: pagination
fs-jun24-team2/phone-catalog pull request #58
Opened 2024-09-22 18:31 UTC by AndriiZakharenko

2024-09-22 20:08 UTC, iyehorova requested changes
Good job!
Please merge the main branch into yours and check the comment below

2024-09-22 20:08 UTC, iyehorova commented on src/modules/ProductsPage/ProductsList/ProductsList.tsx
> +  products: Product[];
if you change  product type, you need change `{Object.values(products).map(product` to {products.map(product

2024-09-22 21:14 UTC, iyehorova approved these changes

2024-09-23 07:12 UTC, OleksiiKislukhin approved these changes
:eyes:

2024-09-23 07:53 UTC, merged