add: notFoundProduct, switch language, fix cursors
fs-jun24-team2/phone-catalog pull request #67
Opened 2024-09-23 16:52 UTC by NavI-Rap0

2024-09-23 16:53 UTC, AndriiZakharenko commented
👀

2024-09-23 16:53 UTC, AndriiZakharenko approved these changes

2024-09-23 18:30 UTC, iyehorova requested changes
Good job!
Please make sure that the image does not overlap the footer and check that it looks good on a mobile layout
And check the comment below

2024-09-23 18:30 UTC, iyehorova commented on src/modules/ProductDetailsPage/ProductNotFoundPage/ProductNotFoundPage.module.scss
> +    background-image: url('/public/img/product-not-found.png');
please replace `/public/img/product-not-found.png` to `/img/product-not-found.png`

2024-09-24 08:07 UTC, AndriiZakharenko approved these changes

2024-09-24 08:18 UTC, AndriiZakharenko commented
👀

2024-09-24 09:55 UTC, iyehorova approved these changes
👀

2024-09-24 10:05 UTC, merged