Add search layout
fs-jun24-team2/phone-catalog pull request #77
Opened 2024-09-24 16:20 UTC by OleksiiKislukhin

2024-09-24 18:49 UTC, iyehorova approved these changes
👀

2024-09-24 21:08 UTC, AndriiZakharenko commented
👀

2024-09-24 21:08 UTC, AndriiZakharenko approved these changes

2024-09-25 04:30 UTC, iyehorova requested changes
Please, check comment below

2024-09-25 04:30 UTC, iyehorova commented on src/modules/ProductsPage/ProductsPage.tsx
> +  const [productList, setProductList] = useState(
We are using redux for the product and it doesn't need to use state

2024-09-25 04:30 UTC, iyehorova commented on src/modules/ProductsPage/ProductsPage.tsx
> +    setSearchFilteredProducts(newProducts);
Apply useFilteredProducts instead this useEffect

2024-09-25 08:07 UTC, iyehorova approved these changes
👀

2024-09-25 08:15 UTC, merged